### ISSUE TITLE
imx6ul-pico-mbl might lose data over UART

### ISSUE THREAD

**Issue by diegorusso** [ARMmbed/meta-mbl#680]
### Description

When pasting long strings onto the UART on imx6ul-pico-mbl, data that the board receives might be corrupted.
We observe this failure in our CI system: it uses ser2net to drive tests and sometime they might fail.

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBLTRIAGE-28*

**Comment by jjohnson-arm** [comment]
Fixed in mbl-os-0.9
