### ISSUE TITLE
imx6ul-pico-mbl wifi and wired issue

### ISSUE THREAD

**Issue by diegorusso** [ARMmbed/meta-mbl#681]
### Description

On imx6ul-pico-mbl we observed that when WiFi and wired connection are both enabled, the wired connection priority doesn't work as expected.
The result is that both WiFi and wired connection are working at the same time.

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBLTRIAGE-27*

**Comment by jjohnson-arm** [comment]
Fixed in mbl-os-0.9
