### ISSUE TITLE
imx7d-pico-mbl wifi is slow to be available after wired interface is disabled

### ISSUE THREAD

**Issue by diegorusso** [ARMmbed/meta-mbl#683]
### Description

WiFi on imx7d-pico-mbl might delay to be available after the eth0 interface has been disabled.
We observed that can take up to 50 seconds after the wired interface is disabled.

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBLTRIAGE-25*
