### ISSUE TITLE
RaspPi3 - I2C Access from a Container - config.json?

### ISSUE THREAD

**Issue by dtischler** [ARMmbed/meta-mbl#695]
### Description

While continuing to experiment with MBL on some RPi3's, I have manually ported over I2C, taking the necessary bits from Raspbian and copying them to their required locations in the MBL rootfs.  (I later learned how to enable it natively by modifying the recipes and building from source, but, my previous method worked fine so I've left it in place).  All said, the host MBL operating system can see i2c sensors in /dev/i2c-1, and read data from them.

However, containers (Alpine linux / Python) built and placed on the Pi cannot see the i2c bus as the /dev/i2c-1 location is not passed through to the container.  My research shows that the config.json file needs to be modified to allow for this, but I have so far been unable to get a working implementation.

The MBL documentation has a hint that this is forthcoming here:

https://os.mbed.com/docs/mbed-linux-os/v0.8/develop-apps/application-development-flow.html#build-examples

"The QR scanner Python application (coming soon) uses its config.json to access the device's hardware resources and persistent memory.  This application is Dockerized (built in a Docker container) - because it's a Python application that (by choice) includes the Python runtime environment with it, as well as the OpenCV library to capture camera frames, it cannot be built and converted to an OCI individually (the way the Hello World C application is built). Instead, it's built and then bundled with all its Python dependencies."

Are there any hints you can provide on what is required in the config.json to pass through the i2c bus, or, is that QR scanner application available somewhere (even in a beta format) so that I can examine it's config.json and try to replicate using that as an example?  Thanks!

### Issue request type

    [x] Question
    [ ] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBLTRIAGE-30*

**Comment by jjohnson-arm** [comment]
Unfortunately work on the QR scanner application has been halted due to customer commitments at this time, and we haven't specifically tried adding i2c into the container so do not have an example we can share.

The good news is that the [FAQ](https://os.mbed.com/docs/mbed-linux-os/v0.8/develop-apps/frequently-asked-questions.html) section does have pointers to the documentation on configuring the containers, specifically you will need to follow the section on [linux devices](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#devices).

**Comment by dtischler** [comment]
Thanks Jeremy, I appreciate the help.  I did see that documentation previously, but will review it again.  

If you do happen to stumble upon any working examples of passing through devices, I'd love to see how it is done!  Thanks.
