### ISSUE TITLE
imx6ul-pico-mbl: cpuidle is disabled

### ISSUE THREAD

**Issue by jjohnson-arm** [ARMmbed/meta-mbl#747]
### Description

To allow OP-TEE to function correctly on IMX6UL the CPU idle power save functionality has been disabled. When CPU idle is enabled, it will power down hardware that is required for OP-TEE to work.

This is the patch commit that disables the cpuidle: 4b77f43

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBLTRIAGE-34*
