### ISSUE TITLE
OP-TEE "Storage concurency" test on iMX8M Mini sometimes fails

### ISSUE THREAD

**Issue by jjohnson-arm** [ARMmbed/meta-mbl#810]
### Description

Intermittently the "Storage concurency" test reports a failure when running the [optee_test](https://github.com/OP-TEE/optee_test) suite 3.6.0 on iMX8M Mini EVK board.

It will return an error code of 255 and show something like the following as output:
```
regression_6016 Storage concurency
regression_6016.1 Storage id: 00000001
    threads: 4, loops: 8
```

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBLTRIAGE-41*
